"""Shared runtime for the service wrappers: transport, bounds, logging, lifecycle.

SAFETY_CLASS: B (provisional)
SAFETY_CLASS_RATIONALE:
    Nothing in this module can alter a computed result. It decodes a request,
    hands validated values to the core, and serialises what comes back; a
    defect here produces a refused or failed request rather than a wrong
    transform. That is why it is classified below the core.

    It is B rather than A because image decoding sits on the clinical data
    path: a decode that silently produced different pixels would be a wrong
    result, not a refusal. That risk is why `decode_image` accepts one image
    mode and one format rather than whatever Pillow will take.

    Provisional pending hazard analysis; see SAFETY_CLASSIFICATION.md.

Everything impure lives here -- sockets, JSON, base64, logging, process
lifecycle -- so that `mri_core` stays a set of pure functions over explicit
typed inputs. That separation is what makes the core reviewable in isolation,
and it is the mechanism the segregation argument rests on.
"""

from __future__ import annotations

import base64
import io
import json
import logging
import os
import sys
from typing import Any

from flask import Flask, Response, request
from PIL import Image, UnidentifiedImageError
from werkzeug.exceptions import HTTPException, RequestEntityTooLarge

from mri_contract.schema import (
    ALGORITHM_VERSION,
    ALLOWED_IMAGE_MODES,
    CONTRACT_VERSION,
    MAX_IMAGE_PIXELS,
    MAX_REQUEST_BYTES,
    MIN_IMAGE_PIXELS,
    SOFTWARE_VERSION,
    ContractViolation,
    ErrorCode,
)

SAFETY_CLASS = "B"
SAFETY_CLASS_PROVISIONAL = True


# --------------------------------------------------------------------------
# Network exposure
# --------------------------------------------------------------------------

# Loopback only, and deliberately not configurable.
#
# The scanner is portable and point-of-care, so it will sit on hospital
# networks that nobody on this team controls. These endpoints have no
# authentication and no transport security, because the orchestrator runs on
# the same machine and the requirement was for process separation, not network
# separation. Under those assumptions an endpoint reachable off-box is a
# defect, and making the bind address an environment variable would mean a
# misconfigured deployment could introduce one silently.
#
# If these ever need to be reachable across a network, that is a change to the
# trust boundary and should arrive as a reviewed change to this line, together
# with the authentication and transport security that would then be required.
LOOPBACK_HOST = "127.0.0.1"


def port_from_env(var_name: str, default: int) -> int:
    """Read a port from the environment, refusing anything unusable.

    Ports are configurable because two services cannot share one and the
    surrounding deployment decides the numbers. The value is validated on the
    way in: a service that silently fell back to a default after a typo would
    leave the orchestrator talking to the wrong process, or to nothing.
    """
    raw = os.environ.get(var_name)
    if raw is None:
        return default
    try:
        port = int(raw)
    except ValueError:
        raise SystemExit(f"{var_name}={raw!r} is not an integer") from None
    if not (1 <= port <= 65535):
        raise SystemExit(f"{var_name}={port} is outside the valid port range")
    return port


# --------------------------------------------------------------------------
# Structured logging
#
# The log is an audit record, not developer output. Every line carries the case
# identifier, the three versions, and the accept or reject decision, so that a
# clinical result can be traced back to the software that produced it and to
# the inputs it was given.
#
# `case_id` is generated by the orchestrator and is opaque here. No patient
# identifier, no image content and no landmark coordinate is logged: the log is
# an operational record, and pixel data or a marked biopsy site in a plaintext
# log is patient data in a place nobody risk-assessed.
# --------------------------------------------------------------------------


def configure_logging(service_name: str) -> logging.Logger:
    logger = logging.getLogger(service_name)
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler(stream=sys.stdout)
    # One JSON object per line. Structured fields rather than free text,
    # because an audit record that has to be parsed with a regular expression
    # is not evidence.
    handler.setFormatter(logging.Formatter("%(message)s"))
    logger.handlers = [handler]
    logger.propagate = False
    return logger


def log_event(logger: logging.Logger, event: str, **fields: Any) -> None:
    record = {
        "event": event,
        "contract_version": CONTRACT_VERSION,
        "software_version": SOFTWARE_VERSION,
        "algorithm_version": ALGORITHM_VERSION,
        **fields,
    }
    logger.info(json.dumps(record, sort_keys=True))


# --------------------------------------------------------------------------
# Image decoding
#
# This is the one place in the transport layer that touches clinical data, and
# the checks here are the ones that could not be done in `mri_contract`: they
# need a decoded image, and the contract package deliberately does not depend
# on Pillow.
# --------------------------------------------------------------------------


def decode_image(png_bytes: bytes, field_path: str) -> Image.Image:
    """Decode PNG bytes into an image, refusing anything outside the contract.

    Three checks, each with a value it inspects and a reason it exists:

      - format: the contract says PNG. Pillow will happily decode a JPEG from
        a field named `..._png_b64`, and a lossy image on a registration path
        is a quiet accuracy loss rather than a visible failure.
      - mode: `helper_functions` builds every intermediate with
        `Image.new("RGB", ...)` and `fillcolor="white"`, and the supplied data
        decodes as RGB. Any other mode is behaviour the transform helpers were
        never exercised against.
      - size: bounded because the device has fixed memory. These are resource
        bounds, not a statement about what a valid scan looks like.
    """
    try:
        img = Image.open(io.BytesIO(png_bytes))
        img.load()
    except (UnidentifiedImageError, OSError, ValueError) as exc:
        raise ContractViolation(
            ErrorCode.IMAGE_DECODE_FAILED, field_path, f"could not decode image: {exc}"
        ) from None

    if img.format != "PNG":
        raise ContractViolation(
            ErrorCode.IMAGE_DECODE_FAILED,
            field_path,
            f"expected PNG, decoded {img.format}",
        )

    if img.mode not in ALLOWED_IMAGE_MODES:
        raise ContractViolation(
            ErrorCode.IMAGE_MODE_UNSUPPORTED,
            field_path,
            f"expected one of {list(ALLOWED_IMAGE_MODES)}, got {img.mode!r}",
        )

    if not (
        MIN_IMAGE_PIXELS <= img.width <= MAX_IMAGE_PIXELS
        and MIN_IMAGE_PIXELS <= img.height <= MAX_IMAGE_PIXELS
    ):
        raise ContractViolation(
            ErrorCode.IMAGE_SIZE_OUT_OF_BOUNDS,
            field_path,
            f"{img.width}x{img.height} outside "
            f"[{MIN_IMAGE_PIXELS}, {MAX_IMAGE_PIXELS}]",
        )

    return img


def encode_image(img: Image.Image) -> str:
    """Encode an image as base64 PNG for the response body.

    PNG because it is lossless: the transformed high-field image is what the
    operator marks a biopsy site on, and a lossy round trip would discard
    detail on the clinical path. No metadata is attached -- the landmark and
    the transform travel as explicit response fields, which is the change this
    whole patch exists to make.
    """
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def require_landmark_in_bounds(
    landmark: tuple[float, float] | None, img: Image.Image, field_path: str
) -> None:
    """A landmark is a pixel index into a specific image.

    Checked here rather than in the contract package because it cannot be
    evaluated without the decoded image it indexes into. A landmark outside the
    image is a marked biopsy site that does not exist in the acquired data, and
    the transform would happily map it to another coordinate that also does not
    exist.
    """
    if landmark is None:
        return
    x, y = landmark
    if not (0 <= x <= img.width - 1 and 0 <= y <= img.height - 1):
        raise ContractViolation(
            ErrorCode.LANDMARK_OUT_OF_BOUNDS,
            field_path,
            f"({x}, {y}) outside image bounds {img.width}x{img.height}",
        )


def require_case_binding(
    request_case_id: str, transform_case_id: str | None, field_path: str
) -> None:
    """The transform must have been issued for the case it is being applied to.

    Derived from the interface contract. See `Transform.issued_for_case_id` for
    what this detects and, importantly, what it does not.
    """
    if transform_case_id is None:
        raise ContractViolation(
            ErrorCode.CASE_ID_MISMATCH,
            field_path,
            "transform carries no issuing case identifier",
        )
    if transform_case_id != request_case_id:
        raise ContractViolation(
            ErrorCode.CASE_ID_MISMATCH,
            field_path,
            f"transform was issued for {transform_case_id!r}, "
            f"request is for {request_case_id!r}",
        )


# --------------------------------------------------------------------------
# Application scaffolding
# --------------------------------------------------------------------------


def json_response(payload: dict[str, Any], status: int) -> Response:
    return Response(
        json.dumps(payload, sort_keys=True),
        status=status,
        mimetype="application/json",
    )


def create_app(service_name: str, logger: logging.Logger) -> Flask:
    """Build a Flask app with the bounds, error handling and probes in place.

    Both services get identical transport behaviour from here. Duplicating it
    would mean two error-handling paths that drift, and an orchestrator that
    has to special-case which service it is talking to.
    """
    app = Flask(service_name)

    # Refuse oversized bodies before reading them into memory. Werkzeug raises
    # RequestEntityTooLarge, translated below into the contract's error code so
    # that the orchestrator sees one error vocabulary rather than two.
    app.config["MAX_CONTENT_LENGTH"] = MAX_REQUEST_BYTES

    # Set once startup succeeds. `/health` answers "is the process alive",
    # `/ready` answers "can it serve a request". They are distinct because the
    # orchestrator has to tell a service that has not finished starting from
    # one that started and is broken -- and retry only the first.
    app.config["READY"] = False

    @app.errorhandler(ContractViolation)
    def _handle_contract_violation(exc: ContractViolation) -> Response:
        log_event(
            logger,
            "request_rejected",
            service=service_name,
            error=exc.code.value,
            field=exc.field,
            outcome="rejected",
        )
        return json_response(exc.as_payload(), 400)

    @app.errorhandler(RequestEntityTooLarge)
    def _handle_too_large(_exc: RequestEntityTooLarge) -> Response:
        violation = ContractViolation(
            ErrorCode.PAYLOAD_TOO_LARGE,
            "<body>",
            f"request exceeds {MAX_REQUEST_BYTES} bytes",
        )
        log_event(
            logger,
            "request_rejected",
            service=service_name,
            error=violation.code.value,
            outcome="rejected",
        )
        return json_response(violation.as_payload(), 413)

    @app.errorhandler(Exception)
    def _handle_unexpected(exc: Exception) -> Response:
        # Fail closed. Anything unanticipated becomes a refusal with a defined
        # code -- never a partial result, never a substituted default. The
        # detail is deliberately generic in the response and complete in the
        # log: an exception message can carry input-derived content, and the
        # response crosses a process boundary.
        if isinstance(exc, HTTPException):
            return json_response(
                {
                    "error": ErrorCode.SCHEMA_INVALID.value,
                    "field": "<request>",
                    "detail": exc.description,
                    "contract_version": CONTRACT_VERSION,
                },
                exc.code or 400,
            )
        logger.exception("unhandled error in %s", service_name)
        log_event(
            logger,
            "request_failed",
            service=service_name,
            error=ErrorCode.INTERNAL_ERROR.value,
            exception_type=type(exc).__name__,
            outcome="failed",
        )
        return json_response(
            {
                "error": ErrorCode.INTERNAL_ERROR.value,
                "field": "<service>",
                "detail": "internal error; see service log",
                "contract_version": CONTRACT_VERSION,
            },
            500,
        )

    @app.get("/health")
    def _health() -> Response:
        return json_response({"status": "alive", "service": service_name}, 200)

    @app.get("/ready")
    def _ready() -> Response:
        ready = bool(app.config["READY"])
        return json_response(
            {"status": "ready" if ready else "not_ready", "service": service_name},
            200 if ready else 503,
        )

    @app.get("/version")
    def _version() -> Response:
        # A regulated device must be able to state which software produced a
        # given clinical result. Three versions because they move
        # independently: the wire contract, the build, and the algorithm.
        return json_response(
            {
                "service": service_name,
                "contract_version": CONTRACT_VERSION,
                "software_version": SOFTWARE_VERSION,
                "algorithm_version": ALGORITHM_VERSION,
            },
            200,
        )

    return app


def read_json_body() -> Any:
    """Parse the request body as JSON, refusing anything that is not.

    `silent=True` because Flask's own 400 page is HTML, and the orchestrator
    branches on this service's error codes. A body that will not parse is a
    contract violation like any other.
    """
    body = request.get_json(silent=True)
    if body is None:
        raise ContractViolation(
            ErrorCode.SCHEMA_INVALID,
            "<body>",
            "request body must be JSON with Content-Type: application/json",
        )
    return body


def serve(app: Flask, logger: logging.Logger, service_name: str, port: int) -> None:
    """Run the service.

    Started by the platform's service manager, or by hand for this MVP -- never
    by the orchestrator. Nothing here assumes a parent process, so moving from
    three terminals to three service unit files changes no code. That is the
    point of the design, and it is what satisfies the requirement that these
    not be subprocesses of the orchestration code.

    `threaded=False` serialises requests. The device images one patient at a
    time, so concurrency here would buy nothing and would mean shared-state
    defects are possible where at present they are not.

    This is Flask's development server, which is appropriate for demonstrating
    the architecture and is not appropriate for the device. A production
    deployment needs a real WSGI server; that is a deployment change, not a
    change to anything above.
    """
    app.config["READY"] = True
    log_event(
        logger,
        "service_started",
        service=service_name,
        host=LOOPBACK_HOST,
        port=port,
    )
    app.run(host=LOOPBACK_HOST, port=port, threaded=False, debug=False)
